### ISSUE TITLE
Adjust API

### ISSUE THREAD

**Issue by matteodem** [matteodem/graphqlizer#12]
So that incrementally changing from graphqlizer CRUD to more complex schemas doesn't result in unreadable code. Also eliminate graphqlContext.

https://gist.github.com/matteodem/9afd3b5401a9aa0127f3cf459a6a0b1a

## TODO

* [x] Add tests
* [x] Add new API methods (crud, resolvers, resolver, typeDefs, typeDef)
* [x] Remove package-lock.json from repo (gitignore)
* [x] Throw deprecation warnings when using old methods
* [x] Add registerType method (see #10)
* [x] Create MIGRATE-1.0.md file that explains how to upgrade
* [x] Update docs
* [x] Remove old docs
* [x] Release v0.* with deprecating warnings
* [x] Update graphqlizer-test-app
* [x] Use new API in Sounds Social
* [x] Include [carbon image](https://carbon.now.sh/?bg=rgba(171,%20184,%20195,%201)&t=dracula&l=javascript&ds=true&wc=true&wa=true&pv=48px&ph=32px&ln=false&code=import%2520%257B%2520crud%252C%2520generateTypeDefsAndResolvers%2520%257D%2520from%2520%27meteor%252Feasy%253Agraphqlizer%27%250Aimport%2520%257B%2520AlienCollection%2520%257D%2520from%2520%27%257B...%257D%27%250A%250Aconst%2520alienSchema%2520%253D%2520crud(%27Alien%27%252C%2520AlienCollection)%250A%250Aconst%2520%257B%2520typeDefs%252C%2520resolvers%2520%257D%2520%253D%2520generateTypeDefsAndResolvers(%257B%250A%2520%2520schemas%253A%2520%255BalienSchema%255D%252C%250A%257D)) in README and link it to github gist
* [ ] Remove old methods / tests
* [ ] Use simpl-schema npm package instead of atmosphere pkg
* [ ] Release v1.0 with warnings
* [ ] Announce release
